### ISSUE TITLE
To many "/" in the request url

### ISSUE THREAD

**Issue by hauketoenjes** [timestee/dart-webdav#3]
Hello, 

i want to use your webdav client in my flutter app. I implemented it the following way:
```dart 
Client client = Client("webdav.webdavserver.com", "user.name", "password", "",
    port: 8080, protocol: "https");

client.ls("/").then((list) {
    print(list);
});
```

The logs say the following: 
`I/flutter ( 6760): [wevdav] http send with method:PROPFIND path: url:https://webdav.webdavserver.com:8080//`

My question is, if i am doing something wrong while using the library or is that a bug (intended behavior)?

Hauke

**Comment by timestee** [comment]
Seems a bug, i will check it later, maybe tomorrow, and pull request welcome.
